- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "DotNet Core 6.X SDK"
    - my_file: "install_dotnetcore6"

    - my_packages:
      - wget
      - curl
      - aria2
      - coreutils

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install dependencies"
    package:
       name: "{{ my_packages }}"
       state: latest

  - name: "{{ my_name }} - create build dirs"
    file:
      path: "{{ retronas_root }}/src/{{ my_file }}"
      owner: root
      group: root
      mode: 0755
      state: directory

  - name: "{{ my_name }} - Download SDK installer"
    get_url:
      url: https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
      dest: "{{ retronas_root }}/src/{{ my_file }}"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - Install DotNet SDK"
    shell:
      cmd: "./dotnet-install.sh --version 6.0.400 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
      chdir: "{{ retronas_root }}/src/{{ my_file }}"
      executable: /bin/bash
    environment:
      DOTNET_ROOT: "{{ retronas_root }}/bin/dotnetcore6"
      DOTNET_INSTALL_DIR: "{{ retronas_root }}/bin/dotnetcore6"

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "dotnetcore6"
    module_state: "present"