# Dependencies
- import_playbook: install_romdir.yml
- import_playbook: install_extradirs.yml

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "MiSTer CIFS"
    - my_file: "install_mister_cifs"

    - top_level_paths:
      - { name: "games",      enabled: yes,  generic: "roms",        systems: yes }
      - { name: "saves",      enabled: yes,  generic: "saves",       systems: yes }
      - { name: "savestates", enabled: yes,  generic: "savestates",  systems: yes }
      - { name: "BIOS",       enabled: yes,  generic: "bios",        systems: yes }
      - { name: "wallpapers", enabled: yes,  generic: "wallpapers",  systems: no  }

  tasks:

  - name: "{{ my_name }} - Include systems map"
    include_vars: "retronas_systems.yml"

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - build top level"
    file:
      path: "{{ retronas_path }}/mister"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory
      mode: "0775"
    notify: "{{ my_name }} - Install Samba"

  - name: "{{ my_name }} - build top level share paths"
    file:
      path: "{{ retronas_path }}/mister/{{ item.name }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory
      mode: "0775"
    with_items:
      "{{ top_level_paths }}"
    when: 
      - item.enabled is true
    notify: "{{ my_name }} - Install Samba"

  - name: "{{ my_name }} - build layout list (set fact)"
    set_fact:
      path_list: "{{ path_list|default([]) }} + ['ln -sf ../../{{ item.1.generic|lower }}/{{ item.0.src }} {{ retronas_path }}/mister/{{ item.1.name }}/{{ item.0.mister }};' ]"
    loop: "{{ system_map|product(top_level_paths)|list }}"
    when:
      - item.1.enabled is true
      - item.0.mister | length > 0
      - item.1.systems is true

  - name: "{{ my_name }} - build systems directory layout"
    shell:
      cmd: "{{ path_list|join('') }}"
    when: path_list is defined
    notify: "{{ my_name }} - Install Samba"

  - name: "{{ my_name }} - configure includes file"
    ini_file:
      path: /etc/samba/smb.conf
      section: mister
      option: "include"
      value: "/etc/samba/retronas_mister.conf"
    notify: "{{ my_name }} - Install Samba"

  - name: "{{ my_name }} - configure retro shares"
    template:
      src: "templates/{{ my_file }}/retronas_mister.conf.j2"
      dest: /etc/samba/retronas_mister.conf
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Install Samba"

  handlers:

  - name: "{{ my_name }} - Install Samba"
    set_fact:
      install_changed: true

- import_playbook: install_samba.yml
  vars:
    changed: "{{ install_changed }}"
  when: install_changed is defined and
        install_changed is true

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "mister_cifs"
    module_state: "present"