- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "apfs-fuse"
    - my_file: "install_apfs-fuse"

    - my_packages:
      - git
      - fuse 
      - libfuse3-dev 
      - bzip2 
      - libbz2-dev 
      - cmake 
      - g++ 
      - libattr1-dev 
      - zlib1g-dev

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install build tools"
    package:
       name: "{{ my_packages }}"
       state: latest

  - name: "{{ my_name }} - Generate scripts"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - build source"
    command:
      cmd: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      creates: "{{ retronas_root }}/bin/apfs-fuse"

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "apfs-fuse"
    module_state: "present"