# Dependencies
- import_playbook: install_cockpit.yml
- import_playbook: install_cockpit-packages.yml

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "retronas"
    - my_file: "install_cockpit-retronas"
    - package_dir: "/usr/share/cockpit"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - create package directory"
    file:
      path: "{{ package_dir }}/{{ my_name }}"
      owner: root
      group: root
      mode: 0755
      state: directory


  - name: "{{ my_name }} - Generate scripts"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - build source"
    command:
      cmd: "{{ retronas_root }}/scripts/{{ my_file }}.sh"

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "cockpit-retronas"
    module_state: "present"