- import_playbook: retronas_system_config_run.yml
  vars:
    module_name: "aria2"

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "aria2"
    - my_file: "install_aria2"

  tasks:

  - meta: end_play
    when: run_play is false 

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml
    
  - name: "{{ my_name }} - install packages"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - aria2

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "aria2"
    module_state: "present"