- import_playbook: retronas_system_config_run.yml
  vars:
    module_prepend: "extradirs"

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "Generic Extra dir(s)"
    - my_file: "install_romdir"

    - top_level_paths:
      - { name: "saves",      enabled: yes, systems: yes }
      - { name: "savestates", enabled: yes, systems: yes }
      - { name: "bios",       enabled: yes, systems: yes }
      - { name: "wallpapers", enabled: yes, systems: no }

  tasks:
    - name: "{{ my_name }}"
      import_tasks: retronas_create_dirs.yml
      when: filehash is defined and
          storedhash is defined and
          filehash.stat.checksum != storedhash.stdout

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "extradirs"
    module_state: "present"