- hosts: localhost
  gather_facts: yes

# Dependencies
- import_playbook: install_dotnetcore3.yml
  when: ansible_architecture == "x86_64"

- hosts: localhost
  gather_facts: yes

  vars:
    - my_name: "SabreTools"
    - my_file: "install_sabretools"

    - my_packages:
      - git
      - coreutils

  tasks:

  - meta: end_play
    when: ansible_architecture != "x86_64"

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install dependencies"
    apt:
       name: "{{ my_packages }}"
       state: latest

  - name: "{{ my_name }} - Prepare installer script"
    template:
      src: templates/{{ my_file }}/{{ my_file }}.sh.j2
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - Run installer"
    shell:
      cmd: "./{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
      chdir: "{{ retronas_root }}/scripts"
      executable: /bin/bash

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "sabretools"
    module_state: "present"
  when: ansible_architecture == "x86_64"