- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "Telnet"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install from repos"
    apt:
       name:
         - telnet
         - telnetd
       state: latest
    notify:
    - "{{ my_name }} - Restart services"

  - name: "{{ my_name }} - Enable startup services"
    service:
      name: inetd
      state: started
      enabled: yes

  handlers:

  - name: "{{ my_name }} - Restart services"
    service:
      name: inetd
      state: restarted

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "telnet"
    module_state: "present"