### migration playbook for issue #21
# this issue is old and the fix is slow so users who haven't updated in a while
# will have to run this manually with 
#
# ansible-playbook migrate_mister_cifs_issue21.yml
#

# Dependencies
- import_playbook: install_samba.yml
- import_playbook: install_romdir.yml
- import_playbook: install_extradirs.yml

- hosts: localhost

  vars:
    - my_name: "MiSTer CIFS"
    - my_file: "install_mister_cifs"

    - top_level_paths:
      - { name: "games",      enabled: yes,  generic: "roms",        systems: yes }
      - { name: "saves",      enabled: yes,  generic: "saves",       systems: yes }
      - { name: "savestates", enabled: yes,  generic: "savestates",  systems: yes }
      - { name: "BIOS",       enabled: yes,  generic: "bios",        systems: yes }
      - { name: "wallpapers", enabled: yes,  generic: "wallpapers",  systems: no  }

  tasks:

  - name: "{{ my_name }} - Include systems map"
    include_vars: "retronas_systems.yml"

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - build top level"
    file:
      path: "{{ retronas_path }}/mister"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory
      mode: "0775"
    notify: "{{ my_name }} - Restart service"

  - name: "get facts for path"
    stat:
      path: "{{ retronas_path }}/mister/{{ item.mister }}"
    with_items:
      - "{{ system_map }}"
    register: mister_stat

  - name: "{{ my_name }} - removing old symlink layout see issue #21"
    file:
      path: "{{ retronas_path }}/mister/{{ item.item.mister }}"
      state: absent
    with_items:
      - "{{ mister_stat.results }}"
    when: item.stat.islnk is defined and item.stat.islnk == True
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - build top level share paths"
    file:
      path: "{{ retronas_path }}/mister/{{ item.name }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory
      mode: "0775"
    with_items:
      "{{ top_level_paths }}"
    when: 
      - item.enabled is true
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - build systems directory layout"
    file:
      src: "../../{{ item.1.generic|lower }}/{{ item.0.src }}"
      dest: "{{ retronas_path }}/mister/{{ item.1.name }}/{{ item.0.mister }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: link
    with_nested:
      - "{{ system_map }}"
      - "{{ top_level_paths }}"
    when: 
      - item.1.enabled is true
      - item.0.mister | length > 0
      - item.1.systems is true
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure includes file"
    ini_file:
      path: /etc/samba/smb.conf
      section: mister
      option: "include"
      value: "/etc/samba/retronas_mister.conf"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure retro shares"
    template:
      src: "templates/{{ my_file }}/retronas_mister.conf.j2"
      dest: /etc/samba/retronas_mister.conf
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - smbd
      - nmbd

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "mister_cifs"
    module_state: "present"