---
- hosts: localhost

  vars:
    my_name: "retronas hash file"
    ini_filename: "retronas_playbook_hash.ini"
    module_name: "retronas_systems"

  tasks:
  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - checksum playbook"
    stat:
      path: "{{ retronas_root }}/ansible/{{ module_name }}.yml"
    register: filehash

  - name: "{{ my_name }} - check for existing hashfile"
    stat:
      path: "{{ retronas_root }}/etc/{{ ini_filename}}"
    register: retronas_hashfile

  - name: "{{ my_name }} - register storedhash"
    shell:
      cmd: "awk -F'= ' '/{{ module_name }}/{print $2}' {{ retronas_root }}/etc/{{ ini_filename }} || echo 0"
    register: storedhash
    ignore_errors: yes

  - name: "{{ my_name }} - Log Package Entry"
    ini_file:
      path: "{{ retronas_root }}/etc/{{ ini_filename }}"
      section: "package"
      option: "{{ module_name }}"
      value: "{{ filehash.stat.checksum }}"
      state: "present"
    when: module_name is defined and 
          filehash is defined and
          storedhash is defined and
          filehash.stat.checksum != storedhash.stdout